### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [2]:
vector = np.random.rand(10)
print(f'Вектор розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1:\n {vector}')
print(f'\nРозмір вектора: {vector.shape}')

Вектор розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1:
 [0.27853795 0.69646725 0.25728151 0.49103396 0.71722705 0.6153129
 0.49197864 0.77976055 0.7250365  0.2345969 ]

Розмір вектора: (10,)


In [3]:
matrix = np.arange(11, 36, 3).reshape(3,3)
print(f'Матриця: \n{matrix}')
print('\nРозмір матриці: ', matrix.shape)

Матриця: 
[[11 14 17]
 [20 23 26]
 [29 32 35]]

Розмір матриці:  (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


###### 2.1. Додайте до кожного значення вектора vector число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.

In [4]:
print((vector+10).round(2))

[10.28 10.7  10.26 10.49 10.72 10.62 10.49 10.78 10.73 10.23]


###### 2.2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.

In [5]:
print(matrix*2)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


###### 2.3. Створіть новий вектор, який містить квадрат кожного vector без циклів.

In [6]:
vector_squared = vector**2
print(vector_squared)

[0.07758339 0.48506663 0.06619377 0.24111435 0.51441465 0.37860997
 0.24204298 0.60802652 0.52567793 0.05503571]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [7]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

###### 3.1. Задані дві матриці A і B розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю result_matrix на екран.

In [8]:
result_matrix = np.dot(B, A)
print(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


###### 3.2. Заданий вектор C розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите result_matrix на вектор C і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [9]:
print(np.dot(result_matrix, C))

[[0.5202]
 [0.2846]]


###### 3.3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [10]:
print(np.dot(result_matrix, D))

[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




###### 4.1. Транспонуйте result_matrix.

In [11]:
print('Оригінальна матриця result_matrix:\n', result_matrix, '\n')
print('Транспонована матриця result_matrix:\n', result_matrix.T)

Оригінальна матриця result_matrix:
 [[0.7281 0.5202]
 [0.2034 0.2846]] 

Транспонована матриця result_matrix:
 [[0.7281 0.2034]
 [0.5202 0.2846]]


###### 4.2. Зробіть транспонування вектора vector і виведіть форму нової структури. Чи бачите ви зміну?

In [12]:
vector_T = vector.T
print('Оригінальний вектор та його форма:', vector, vector.shape, sep = '\n')
print('\nТранспонований вектор та його форма:', vector_T, vector_T.shape, sep = '\n')

Оригінальний вектор та його форма:
[0.27853795 0.69646725 0.25728151 0.49103396 0.71722705 0.6153129
 0.49197864 0.77976055 0.7250365  0.2345969 ]
(10,)

Транспонований вектор та його форма:
[0.27853795 0.69646725 0.25728151 0.49103396 0.71722705 0.6153129
 0.49197864 0.77976055 0.7250365  0.2345969 ]
(10,)


Немає зміни у формі вектора vector розмірністю (10,) після операції транспонування.

###### 4.3. Використайте операцію numpy.expand_dims над вектором vector з аргументом axis=1. Запишіть отриманий результат в змінну column_vector і виведіть на екран. Порівняйте з vector.

In [13]:
column_vector = np.expand_dims(vector, axis=1)

print('Вектор vector та його форма:', vector, vector.shape, sep = '\n')
print('\nВектор column_vector та його форма:', column_vector, column_vector.shape, sep = '\n')


Вектор vector та його форма:
[0.27853795 0.69646725 0.25728151 0.49103396 0.71722705 0.6153129
 0.49197864 0.77976055 0.7250365  0.2345969 ]
(10,)

Вектор column_vector та його форма:
[[0.27853795]
 [0.69646725]
 [0.25728151]
 [0.49103396]
 [0.71722705]
 [0.6153129 ]
 [0.49197864]
 [0.77976055]
 [0.7250365 ]
 [0.2345969 ]]
(10, 1)


Оригінальний вектор **vector** - це вектор-рядок з розмірністю (10,).

Вектор **column_vector** - це вектор-стовпець з розмірністю (10, 1).

###### 4.4. Зробіть транспонування column_vector, виведіть результат на екран разом з розмірностями отриманої структури.

In [14]:
column_vector_T = column_vector.T

print('\nТранспонований вектор column_vector та його форма:', column_vector_T, column_vector_T.shape, sep = '\n')


Транспонований вектор column_vector та його форма:
[[0.27853795 0.69646725 0.25728151 0.49103396 0.71722705 0.6153129
  0.49197864 0.77976055 0.7250365  0.2345969 ]]
(1, 10)
