В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


In [31]:
import numpy as np

In [32]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [33]:
z = [-2, -1, 0, 1, 2]
y = []
for i in range(len(z)):
    y.append(sigmoid(z[i]))

display(y)

[np.float64(0.11920292202211755),
 np.float64(0.2689414213699951),
 np.float64(0.5),
 np.float64(0.7310585786300049),
 np.float64(0.8807970779778823)]



#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


In [34]:
def hypothesis(theta, X):
    return 1 / (1 + np.exp(-np.dot(X, theta.T)))

In [35]:
theta = np.array([0.5, -0.5])
print(theta)
print(theta.shape)

[ 0.5 -0.5]
(2,)


In [36]:
X = np.array([1, 2, 1, -1, 1, 0, 1, 1]).reshape(4,2)
print(X)
print(X.shape)

[[ 1  2]
 [ 1 -1]
 [ 1  0]
 [ 1  1]]
(4, 2)


In [37]:
hypothesis(theta, X)

array([0.37754067, 0.73105858, 0.62245933, 0.5       ])

#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

In [38]:
# Створення даних для обчислень

theta = np.array([0.5, -0.5])
print('Theta:\n', theta)
X = np.array([1, 2, 1, -1, 1, 0, 1, 1]).reshape(4,2)
print('X:\n', X)
y = np.array([1, 0, 1, 0])
print('y:\n', y)

Theta:
 [ 0.5 -0.5]
X:
 [[ 1  2]
 [ 1 -1]
 [ 1  0]
 [ 1  1]]
y:
 [1 0 1 0]


In [39]:
# Функція для обчислення градієнтів функції втрат для логістичної регресії. Крім numpy використовуємо також функцію hypothesis із завдання 2. 

def compute_gradient(theta: np.ndarray, X: np.ndarray, y: np.ndarray) -> np.ndarray:
    """
    Calculates the gradient of loss function for logistic regression. Please consider the correct shapes of arguments mentioned below.

    Args:
    - theta (np.ndarray): parameter vector of shape (n, )
    - X (np.ndarray): feature matrix of shape (m, n)
    - y (np.ndarray): target vector of shape (m, )

    Returns:
    - gradient (np.ndarray): gradient vector of shape (n, )
    """
    m = len(y)
    h = hypothesis(theta, X)
    gradient = (1 / m) * np.dot(X.T, h - y)
    return gradient

# Обчислення градієнтів
compute_gradient(theta, X, y)

array([ 0.05776464, -0.36899431])


#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. Напишіть функцію `full_batch_gradient_descent(X, y, lr=0.1, epochs=100)`, яка реалізує алгоритм Full градієнтного спуску для логістичної регресії. Використовуйте такі формули:
   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


In [40]:
# Використовуємо X та y з попередніх завдань 
print('X:\n', X)
print('y:\n', y)

X:
 [[ 1  2]
 [ 1 -1]
 [ 1  0]
 [ 1  1]]
y:
 [1 0 1 0]


In [41]:
# Функція, яка реалізує алгоритм full_batch градієнтного спуску для логістичної регресії.
# Використовуються також попередньо створені функції: (1) hypothesis та (2) compute_gradient

def full_batch_gradient_descent(X, y, lr = 0.1, epochs = 100):
    theta = np.array([0.5, -0.5]) # Початкові параметри
    m = len(y)
    for _ in range(epochs):
        y_pred = hypothesis(theta, X)
        gradient = compute_gradient(theta, X, y)
        theta[0] = theta[0] - lr * gradient[0]
        theta[1] = theta[1] - lr * gradient[1]
    return theta

In [42]:
# Результат обчислень

theta_fbgd = full_batch_gradient_descent(X, y)
theta_fbgd

array([-0.17775255,  0.69821883])

#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

##### 5.1. Функція `predict_proba(theta, X)`

In [43]:
def predict_proba(theta, X):
    y_pred_proba = hypothesis(theta, X)
    return y_pred_proba # повертає ймовірності належності вхідних даних до класу y = 1

##### 5.2. Функція `predict(theta, X, threshold=0.5)`

In [44]:
def predict(theta, X, threshold=0.5):
    y_pred_proba = hypothesis(theta, X)
    y_pred = []
    for i in range(len(y_pred_proba)):
        if y_pred_proba[i] < threshold:
            y_pred.append(0)
        else:
            y_pred.append(1)
    return y_pred

##### 5.3. Функція `accuracy(y_true, y_pred)`

In [45]:
def accuracy(y_true, y_pred):
    m = len(y_true)
    accuracy = sum(y_true == y_pred) / m
    return accuracy

##### 5.4. Обчислення

In [46]:
y_pred_proba = predict_proba(theta_fbgd, X)
print('Імовірності належності до класу 1:')
y_pred_proba

Імовірності належності до класу 1:


array([0.77183207, 0.2940133 , 0.4556785 , 0.62725679])

In [47]:
y_pred = predict(theta_fbgd, X, threshold=0.5)
print('Передбачені класи:')
y_pred

Передбачені класи:


[1, 0, 0, 1]

In [48]:
acc = accuracy(y, y_pred)
print('y_true:', y)
print('y_pred:', y_pred)
print('Точність:')
print('accuracy =',acc*100,'%')

y_true: [1 0 1 0]
y_pred: [1, 0, 0, 1]
Точність:
accuracy = 50.0 %
